### ISSUE TITLE
Hardfault when executing code

### ISSUE THREAD

**Issue by vChavezB** [bogdanm/udynlink#3]
Hi,
I was testing the code on an STM32 with an M4 cortex CPU. I used the mkmodule script to compile a simple function:

```
void dummyFun(void){
}
```

And got the following image

```
static const unsigned char dummyFunction_module_data[] = {
    0x55, 0x44, 0x4C, 0x4D, 0x00, 0x00, 0x00, 0x00, 0x2C, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x30,
    0x00, 0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x50, 0x03, 0x00, 0x00, 0x00, 0x64, 0x75, 0x6D, 0x6D, 0x79, 0x46, 0x75, 0x6E, 0x63, 0x74, 0x69, 0x6F, 0x6E, 0x00, 0x64, 0x75, 0x6D, 0x6D, 0x79, 0x46,
    0x75, 0x6E, 0x00, 0x00, 0x70, 0x47, 0x2D, 0xE9, 0x00, 0x42, 0x03, 0xB4, 0x4F, 0xF0, 0x1C, 0x01, 0x09, 0x68, 0x78, 0x46, 0x88, 0x47, 0x81, 0x46, 0x03, 0xBC, 0xFF, 0xF7, 0xF3, 0xFF, 0xBD, 0xE8,
    0x00, 0x82, 0x00, 0x00
};
```

Code used to call the image

```
	udynlink_error_t udynLinkError;
	uint32_t ramSize=0; 
	udynlink_set_debug_level(UDYNLINK_DEBUG_INFO);
	udynlink_module_t * p_mod= udynlink_load_module(dummyFunction_module_data,NULL,ramSize,UDYNLINK_LOAD_MODE_COPY_ALL,&udynLinkError);
	udynlink_sym_t sym; // symbol structure
	udynlink_lookup_symbol(p_mod, "dummyFun", &sym); // p_mod is a handle to the module (returned by udynlink_load_module)
	void (*dummyFun)(void) = (void (*)(void))sym.val; // convert the symbol value to the proper function type
	dummyFun(); // call the function
```

 I checked the debug messages and it allocates the 100 bytes of the module image correctly and get no errors until the last line where I call the function. I get a hardfault and the INVSTATE flag is set to 1 from the UsageFault Status Register (USFR).

I am lost to this point to check how I can further debug this error or perhaps something else that I am missing for executing the code from RAM on this particular STM32 microcontroller.

**Comment by vChavezB** [comment]
The problem seems to be located when the function at address `0x1C` is called. What function should be called when executing the code at memory address "0x1C"? From my debug session I found out that `blx r1` executes instruction `0x00000000` since its pointing to the absolute memory address `0x1C` of the microcontroller and not to the intended function mentioned in the Readme

```
push    {r9, lr}
push    {r0, r1}
mov     r1, #0x1c
ldr     r1, [r1]
mov     r0, pc
blx     r1
mov     r9, r0
pop     {r0, r1}
bl      {{actname}}
pop     {r9, pc}
```

**Comment by vChavezB** [comment]
I fixed the issue by modfying the assembly template and assigning directly in C code the correct value to R9 for the LOT, since for some reason (do not understand completely the asm wrapper) it does not load the address of the LOT and creates a hardfault by executing code from absolute address 0x1C.
Ran the Tests with the actual HW instead of QEMU and now its working as expected :) 
writing this down in case someone stumbles upon this issue.

Edit: The reason the author executes code in addres 0x1C is because in the project files for the stm32 uc the address of the function that loads the LOT in R9 is manually initialized in the ISR vector section. 
`/tests/qemu_host/system/src/cmsis/vectors_stm32f429xx.c`

**Comment by paulrouget** [comment]
> I fixed the issue by modfying the assembly template and assigning directly in C code the correct value to R9 for the LOT

@vChavezB I'm running into the same issue. How did you do that?

**Comment by vChavezB** [comment]
Hi Paul, 

You need to load the address where the LOT is in your program (RAM). This can be retrieved when you load your Udynlink module and have a pointer to `udynlink_module_t`. From this pointer you can use `ram_base` which points to the LOT. Then you need to modify the assembly wrapper or use your own to load this value to register R9. I also discussed this in the ST forum so you can use the discussion there to guide you:

https://community.st.com/t5/stm32-mcus-products/load-dynamic-functions-during-runtime-stm32l431/td-p/260092

Just as a word of advice, you have to be careful when using assembly as compiler optimizations might make your code behave differently. For example I saw that GCC behaved fine while clang did some changes, so its better to work directly in assembly when altering the registers of the Cortex-M CPU.
Regards,
Victor

**Comment by paulrouget** [comment]
@vChavezB thank you! I'll see how that goes.

**Comment by paulrouget** [comment]
@vChavezB This flies above my head. I don't have any experience with assembly, so I'm kind of struggling.

This is what my code look like:

Compiling with GCC, `-std=c99` `-O3`. Because I'm using `gcc -std=c99`, I have to use `__asm` instead of `asm`.

```c
    udynlink_error_t ue;
    udynlink_set_debug_level(UDYNLINK_DEBUG_INFO);
    udynlink_module_t* mod = udynlink_load_module(buffer, NULL, size, UDYNLINK_LOAD_MODE_COPY_ALL, &ue);
    if (mod == NULL) {
      NRF_LOG_ERROR("udynlink_load_module failed");
    } else {
      udynlink_sym_t sym;
      udynlink_sym_t* sym_ptr = udynlink_lookup_symbol(mod, "foobar", &sym);
      if (sym_ptr == NULL) {
        NRF_LOG_ERROR("udynlink_lookup_symbol failed");
      } else {
        NRF_LOG_INFO("mod->ram_base: 0x%x", mod->ram_base);

        int localGOTValue = mod->ram_base;

        void (*dynamicFunctionPtr)() = (void (*)())sym.val;


        register int * r9_register __asm ("r9"); //Assign a variable to r9
        __asm("stmdb   sp!, {r9}"); //Backup R9
        // Not sure why, in the original snippet, it was not `*r9_register = ` but `r9_register =`. Which doesn't compile.
        *r9_register = localGOTValue; //Point R9 to GOT
        dynamicFunctionPtr(); //Executes my function from Ram
        __asm("ldmia.w sp!, {r9}"); //Restore Value of R9

        NRF_LOG_INFO("OK");
      }
    }


```

My module:
```c
void foobar() {
}
```

```asm
    .syntax unified
    .arch armv7-m

    .text
    .thumb


    .thumb_func
    .align 1
    .globl foobar
    .type foobar, %function
    .extern __3858f6223__foobar
    .type __3858f6223__foobar, %function
foobar:
    push    {r9, lr}
    push    {r0, r1}
    mov     r1, #0x1c
    ldr     r1, [r1]
    mov     r0, pc
    blx     r1
    mov     r9, r0
    pop     {r0, r1}
    bl      __3858f6223__foobar
    pop     {r9, pc}

    .size   foobar, . - foobar


    .end
````

**Comment by paulrouget** [comment]
I haven't changed the asm template.

**Comment by paulrouget** [comment]
Stepping through the assembly code, first time doing that with GDB, pretty cool :)

It hands here:

```asm
ldr     r2, [r5, #4]
ldr     r3, [sp, #24]
str.w   r9, [sp, #-4]!
str.w   r2, [r9]
blx     r3 ; Hangs here.
```

I have no idea what I'm looking at.

**Comment by paulrouget** [comment]
I'm starting to understand what's happening here.

I removed all the asm code from the template that calls `udynlink_get_lot_base`.
I don't even need to call it in C because it just returns `ram_base`.
So in C, I save the original value of R9, set R9 to `ram_base`, execute my foobar function and restore R9.

Still not working, but I might be running into GCC over optimising my ASM C calls.

Investigating more…

**Comment by paulrouget** [comment]
It's working now.

The usage of `__isr_vector` and `0x1C` were kind of confusing.

For future reference, the ASM template can be simplified with:

```asm
{{s}}:
    push    {r9, lr}
    push    {r0, r1}
    ldr     r1, =0xXXXXXXXX
    mov     r0, pc
    blx     r1
    mov     r9, r0
    pop     {r0, r1}
    bl      {{actname}}
    pop     {r9, pc}
```

Where `0xXXXXXXXX` is the address of `udynlink_get_lot_base`.
